### ISSUE TITLE
TCP and UPD, losing log events / Flush

### ISSUE THREAD

**Issue by thnk2wn** [splunk/splunk-library-dotnetlogging#14]
For TCP and UDP listeners, how can we make logging still work even if the buffer never hits the min size to start logging? Or if it one batch gets logged later and then more are sitting there, how do we make sure we don't lose log data? It seems it should auto flush on disposal or at a minimum we could manually flush but neither works.
    
    public static class LogUsingTcpTraceListener
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        // I think it uploads in batches though.
        private static TcpTraceListener CreateSplunkListener()
        {
            // note you have to create a TCP port in splunk UI:
            // http://splunk:8000/en-US/manager/search/data/inputs/tcp/raw
            var listener = new TcpTraceListener("splunk", 10000, new ExponentialBackoffTcpReconnectionPolicy());
            
            return listener;
        }

        public static void Test(string[] args)
        {
            //HACK: temp test to try to force log send
            Trace.AutoFlush = true; 

            Trace.Listeners.Clear();

            using (var listener = CreateSplunkListener())
            {
                Trace.Listeners.Add(listener);

                Logger.Info("TcpTraceListener setup. Test app started with {0} argument(s)", args.Length);

                // HACK: attempt to write to trace normally without going through NLog trace target 
                Trace.WriteLine($"TcpTraceListener setup (2). Test app started with {args.Length} argument(s)");

                //HACK: temp test to try to force log send
                listener.Flush();
                listener.Close();
            }
        }
    }

**Comment by glennblock** [comment]
Hi @thnk2wn 

Thanks for posting. As I mentioned in the answers post, the issue with TCP and UDP is that Splunk has a buffer on the server side, I believe it is 1mb, which needs to be filled BEFORE it will write to the index. If you close the TCP socket, it will force the buffer to empty, but that is probably not what you want to do. Calling flush on the client will not change the behavior, as this is something backed into Splunk on the server side.

My suggestion would be to test sending larger amounts of data, and you should see it automatically get indexed. Also it is important to note that our loggers all push data asynchronously while the Trace Listener interfaces are sync. For this reason, if you are testing, you'll want to have a delay, or in a console app a Console.ReadLine() to ensure the data is flushed before the process dies.

**Comment by gregberns** [comment]
If this is still a valid issue, it would be helpful to have something in the docs describing the need to flush especially in console apps (just spent 2 hrs trying to figure this one out). 
For some reason I seem to need to flush and close both 'HttpEventCollectorTraceListener' and 'TraceSource'.
Just wanted to comment to maybe prevent someone else from having to deal with this.
