### ISSUE TITLE
Invalid timestamp format in HttpEventCollectorEventInfo with Swedish locale

### ISSUE THREAD

**Issue by magnuswiderberg** [splunk/splunk-library-dotnetlogging#19]
* Splunk.Logging.TraceListener version: 1.6.1
* Platform version: Windows 10 Enterprise
* Framework version: .Net 4.5.2, Visual Studio 2015
* Splunk version: 6.5.0

I use HttpEventCollectorTraceListener for sending data to Splunk and then the Timestamp format with CurrentCulture set to "sv-SE" will be <code>"time":"1479456012,045"</code> instead of <code>"time":"1479456012.045"</code>, and the request will be rejected by Splunk.

I can work around it with e.g.
<code>System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;</code>
but I wonder if this should be handled by the lib?

**Comment by shakeelmohamed** [comment]
Hi @magnuswiderberg,

This is definitely something the library should do for you. We made a similar change for the Java logging library - https://github.com/splunk/splunk-library-javalogging/commit/a946e9ff075b82f64fc02fd677e9c727db3fc954.

We're open to a pull request if you're interested in making the change

**Comment by magnuswiderberg** [comment]
Ok, nice. I will make a pull request.

**Comment by belaie** [comment]
We are having the same issue, do you know if this is resolved?

**Comment by magnuswiderberg** [comment]
Hi @belaie,

I submitted a pull request here: https://github.com/splunk/splunk-library-dotnetlogging/pull/20, which solves the problem. It hasn't been merged, but you could do a work-around in your code similar to it.

**Comment by shakeelmohamed** [comment]
We've merged #20 into the develop branch. I can't promise a release date, but if there's interest I can help raise the urgency.

**Comment by xpac1985** [comment]
I added a comment to the PR because the fix never made it to the release...
