### ISSUE TITLE
Getting issue in integrating splunk with .net core 2.0

### ISSUE THREAD

**Issue by JyotiNath** [splunk/splunk-library-dotnetlogging#50]
I am following the steps mentioned in below link for net core integration with splunk but I am getting System.Net.Sockets.SocketException: Broken pipe.
Please let me know if I am changing it correctly or not. Any suggestions and pointers please.

https://github.com/vtex/SplunkLogger/blob/master/src/SampleWebAPI/Startup.cs

**Comment by JyotiNath** [comment]
Any updates on this issue

**Comment by shakeelmohamed** [comment]
@JyotiNath the library you've linked to is not officially supported by Splunk. Please ask the project owner for guidance as we are unfamiliar and unable to assist you with third-party libraries.
