### ISSUE TITLE
Timestamp formatting broken for various locales

### ISSUE THREAD

**Issue by xpac1985** [splunk/splunk-library-dotnetlogging#55]
With reference to #19 and #20, there are still issues with timestamping when the lib is being run e.g. on Swedish or German locale.
The offending line is:
https://github.com/splunk/splunk-library-dotnetlogging/blob/master/src/Splunk.Logging.Common/HttpEventCollectorEventInfo.cs#L179

It is:
`Timestamp = epochTime.ToString("#.000", Thread.CurrentThread.CurrentCulture);`
It should be:
`Timestamp = epochTime.ToString("#.000", System.Globalization.CultureInfo.InvariantCulture);`

I'm relaying this information for a colleague, I don't do any C/.NET developement myself.

**Comment by fantavlik** [comment]
Thanks @xpac1985 I put up a PR with this fix and updated our tests accordingly, I'll have one of our team review the changes.

**Comment by shakeelmohamed** [comment]
Addressed in #56
