### ISSUE TITLE
TCP Logging

### ISSUE THREAD

**Issue by glennblock** [splunk/splunk-library-dotnetlogging#7]
Currently we only support UDP logging. This doesn't work well for cloud scenarios. We should add a Splunk TCPTraceListener and TCPEventSink

**Comment by shakeelmohamed** [comment]
Looks like this is done: [`TCPTraceListener`](https://github.com/splunk/splunk-library-dotnetlogging/blob/master/src/Splunk.Logging.TraceListener/TcpTraceListener.cs) [`TCPEventSink `](https://github.com/splunk/splunk-library-dotnetlogging/blob/master/src/Splunk.Logging.SLAB/TcpEventSink.cs)
